server:
  port: 8700
spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false
  instance: 
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost   
  server: 
    #enableSelfPreservation: false
    eviction-interval-timer-in-ms: 5000